version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2404:current #
    steps:
      - checkout
      - run:
          name: 安装依赖
          command: npm install
      - run:
          name: 运行测试
          command: curl ipinfo.io

workflows:
  build_and_test:
    jobs:
      - build